apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp
spec:
  replicas: {{ .Values.bankapp.replicaCount }}
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
      - name: bankapp
        image: {{ .Values.bankapp.image }}:{{ .Values.bankapp.tag }}
        ports:
        - containerPort: {{ .Values.bankapp.containerPort }}
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://{{ .Values.bankapp.db.host }}:{{ .Values.bankapp.db.port }}/{{ .Values.bankapp.db.dbName }}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        - name: SPRING_DATASOURCE_USERNAME
          value: {{ .Values.bankapp.db.username }}
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.bankapp.db.secretName }}
              key: MYSQL_ROOT_PASSWORD

