apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.bankapp.servicePort }}
    targetPort: {{ .Values.bankapp.containerPort }}
  selector:
    app: bankapp

