apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
  - port: {{ .Values.database.containerPort }}
    targetPort: {{ .Values.database.containerPort }}

